[versions]
assertj = "3.27.6"
detekt = "1.23.8"
finchly = "0.1.1"
koog = "0.4.2"
dokka = "2.1.0"
junit = "6.0.1"
kotest = "6.0.5"
kotlin = "2.1.21"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
kover = "0.9.3"
ktor = "3.3.3"
langchain4j = "1.9.1"
mokksy = "0.5.0-RC1"
mockk = "1.14.6"
nexus-publish = "2.0.0"
spring-ai = "1.0.3"
slf4j = "2.0.17"
spotless = "8.1.0"
openai-kotlin = "4.0.1"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
finchly = { module = "me.kpavlov.finchly:finchly", version.ref = "finchly" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
koog = { module = "ai.koog:koog-agents", version.ref = "koog" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
langchain4j-bom = { group = "dev.langchain4j", name = "langchain4j-bom", version.ref = "langchain4j" }
langchain4j-kotlin = { group = "dev.langchain4j", name = "langchain4j-kotlin" }
langchain4j-openai = { group = "dev.langchain4j", name = "langchain4j-open-ai" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mokksy-openai = { group = "me.kpavlov.aimocks", name = "ai-mocks-openai", version.ref = "mokksy" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
spring-ai-bom = { group = "org.springframework.ai", name = "spring-ai-bom", version.ref = "spring-ai" }
spring-ai-client-chat = { group = "org.springframework.ai", name = "spring-ai-client-chat", version.ref = "spring-ai" }
spring-ai-core = { group = "org.springframework.ai", name = "spring-ai-core" }
spring-ai-gemini = { group = "org.springframework.ai", name = "spring-ai-vertex-ai-gemini" }
spring-ai-openai = { group = "org.springframework.ai", name = "spring-ai-openai" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
openai-client = { module = "com.aallam.openai:openai-client", version.ref = "openai-kotlin" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kover-aggregation = { id = "org.jetbrains.kotlinx.kover.aggregation", version.ref = "kover" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
